name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: "chat-67-67"
            site: "deltasucks"
          - project: "c0delistener"
            site: "studyhard"
          - project: "chat-283f4"
            site: "nodelta"

    steps:
      - uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        # We combine 'hosting' and the 'site id' into the --only flag
        run: firebase deploy --only hosting:${{ matrix.site }} --project ${{ matrix.project }}